<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the Pod Tailwind theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function pod_tailwind_preprocess_html(array &$variables): void {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function pod_tailwind_preprocess_page(array &$variables): void {

}

function pod_tailwind_preprocess_block__system_branding_block(array &$variables): void {
$variables['attributes']['class'][] = 'text-2xl font-bold text-gray-800 w-[100px]';
}

function pod_tailwind_preprocess_menu__main(array &$variables): void {
  $variables['attributes']['class'][] = 'flex space-x-6';
}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function pod_tailwind_preprocess_node(array &$variables): void {

}
